# Generated by Django 5.1.5 on 2025-03-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=15, verbose_name='姓名')),
                ('age', models.SmallIntegerField(default=0, verbose_name='年龄')),
                ('sex', models.BooleanField(default=True, verbose_name='性别')),
                ('classmate', models.CharField(db_column='class', db_index=True, default='', max_length=50, verbose_name='班级编号')),
                ('mobile', models.CharField(max_length=20, unique=True, verbose_name='手机号码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='个性签名')),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '未入学'), (3, '已毕业')], default=1, verbose_name='毕业状态')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': 'student',
            },
        ),
    ]
