# Generated by Django 5.1.5 on 2025-03-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_created_time_student_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (2, '未入学'), (3, '已毕业')], default=1, null=True, verbose_name='毕业状态'),
        ),
    ]
